name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Create data Folder
        run: mkdir -p data
      - name: Pull Docker image
        run: sudo docker pull mrsunglasses/pastepy
      - name: Delete Old docker container
        run: sudo docker rm -f pastepyprod || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 -v $(pwd)/data:/project/data --name pastepyprod mrsunglasses/pastepy
